name: Release Builder Backend

on:
  push:
    tags:
      - 'builder-backend-v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nodus-factory/builder-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        id: v
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "version=${TAG#builder-backend-v}" >> $GITHUB_OUTPUT
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.v.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest